/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/api-keys': typeof ApiKeysRoute
  '/auth': typeof AuthRoute
  '/batch': typeof BatchRoute
  '/brand-kit': typeof BrandKitRoute
  '/editor': typeof EditorRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/api-keys': typeof ApiKeysRoute
  '/auth': typeof AuthRoute
  '/batch': typeof BatchRoute
  '/brand-kit': typeof BrandKitRoute
  '/editor': typeof EditorRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/api-keys': typeof ApiKeysRoute
  '/auth': typeof AuthRoute
  '/batch': typeof BatchRoute
  '/brand-kit': typeof BrandKitRoute
  '/editor': typeof EditorRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/api-keys'
    | '/auth'
    | '/batch'
    | '/brand-kit'
    | '/editor'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/api-keys'
    | '/auth'
    | '/batch'
    | '/brand-kit'
    | '/editor'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/api-keys'
    | '/auth'
    | '/batch'
    | '/brand-kit'
    | '/editor'
    | '/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AuthRoute: typeof AuthRoute
  BatchRoute: typeof BatchRoute
  BrandKitRoute: typeof BrandKitRoute
  EditorRoute: typeof EditorRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  ApiKeysRoute: ApiKeysRoute,
  AuthRoute: AuthRoute,
  BatchRoute: BatchRoute,
  BrandKitRoute: BrandKitRoute,
  EditorRoute: EditorRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
